### ISSUE TITLE
FutureWarning: `multichannel` is a deprecated argument name for `pyramid_gaussian`

### ISSUE THREAD

**Issue by jasper-tms** [NeLy-EPFL/ofco#5]
I ran ofco for the first time on some CC single-plane xz data and something like 90% of the lines in the logs were repetitions of these two lines:

> /home/phelps/venvs/ofco/lib/python3.7/site-packages/ofco/optflow.py:35: FutureWarning: `multichannel` is a deprecated argument name for `pyramid_gaussian`. It will be removed in version 1.0. Please use `channel_axis` instead.
  multichannel=False,
/home/phelps/venvs/ofco/lib/python3.7/site-packages/ofco/optflow.py:42: FutureWarning: `multichannel` is a deprecated argument name for `pyramid_gaussian`. It will be removed in version 1.0. Please use `channel_axis` instead.
  I2, c2fLevels - 1, param["c2fSpacing"], smooth_sigma, multichannel=False

Presumably this just requires a small update to resolve.

**Comment by jonasfbraun** [comment]
This has been resolved by commit 8d40ce3 by VLR.
